# Generated by Django 3.1.11 on 2021-06-02 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrscnetra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='auto_increment_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='system',
            name='ip_address',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
