# Generated by Django 3.1.11 on 2021-06-02 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nrscnetra', '0002_auto_20210602_2242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='system',
            old_name='auto_increment_id',
            new_name='system_id',
        ),
    ]
