# Generated by Django 3.1.11 on 2021-06-03 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nrscnetra', '0004_job_jobdef'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='system',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='nrscnetra.system'),
            preserve_default=False,
        ),
    ]
